heading = "Publications"

# List only papers available online, with a link to the paper, in reverse chronological order.
# The homepage shows the first ten entries.

[[manuscripts]]
title = "Fiat-Shamir Goes Rational (Or: On the Perils of Sublinear Verification)"
status = "ASIACRYPT"
year = "2026"
citation = { key = "EPRINT:CamDat24", version = "ePrint version · 2024" }
links = [{ label = "ePrint", url = "https://eprint.iacr.org/2024/1645" }]
authors = [
  { name = "Matteo Campanelli", url = "https://binarywhales.com/" },
  { name = "Agni Datta", url = "/" },
]
