[[entries]]
title = "Fiat-Shamir Goes Rational"
venue = "Cryptography Group, Bar-Ilan University"
venue_url = "https://crypto.biu.ac.il/"
date = "May 2025"
links = []

[[entries]]
title = "Fiat-Shamir Goes Rational"
venue = "Cryptography and Security Group, Aarhus University"
venue_url = "https://cs.au.dk/research/cryptography-and-cyber-security/"
date = "Dec 2024"
links = []

[[entries]]
title = "Windows Registry Forensic Analysis"
venue = "Workshop on Windows Forensics, CAPT"
date = "Jun 2023"
links = []

[[entries]]
title = "Oshin OS: Risk Mitigation for Minors"
venue = "First National Conference on Emerging Technologies, CAPT"
date = "Feb 2023"
links = []
