//! Browser Wasm compilation and audited, atomic site output activation.
use crate::{
    audit,
    tools::{cargo, run},
};
use anyhow::{Context, Result};
use std::fs;
use std::hash::{DefaultHasher, Hash, Hasher};
use std::path::Path;
use wasm_bindgen_cli_support::Bindgen;

pub(super) fn build(root: &Path) -> Result<()> {
    build_browser_wasm(root)?;
    let candidate = root.join("target/site-output/current");
    let report = sitegen::build(&sitegen::BuildConfig {
        workspace_root: root.to_path_buf(),
        output_dir: candidate.clone(),
    })?;
    audit::run(root, &candidate)?;
    replace_directory(
        &candidate,
        &root.join("public"),
        &root.join("target/site-output/public-previous"),
    )?;
    println!(
        "built {} pages at {} (asset key {})",
        report.page_count,
        root.join("public").display(),
        report.cache_key
    );
    Ok(())
}

fn build_browser_wasm(root: &Path) -> Result<()> {
    run(
        cargo(root)?.current_dir(root).args([
            "build",
            "--locked",
            "--release",
            "--package",
            "webapp",
            "--target",
            "wasm32-unknown-unknown",
        ]),
        "building browser Wasm",
    )?;

    let input = root.join("target/rustup/wasm32-unknown-unknown/release/webapp.wasm");
    let parent = root.join("target/site-assets");
    let staging = parent.join("wasm-next");
    let output = parent.join("wasm");
    let backup = parent.join("wasm-previous");
    if staging.exists() {
        fs::remove_dir_all(&staging).with_context(|| format!("removing {}", staging.display()))?;
    }
    fs::create_dir_all(&staging).with_context(|| format!("creating {}", staging.display()))?;
    let mut bindgen = Bindgen::new();
    bindgen.input_path(&input).out_name("webapp");
    bindgen.web(true)?;
    bindgen.typescript(false);
    bindgen.omit_default_module_path(false);
    bindgen.generate(&staging)?;
    let generated_js = staging.join("webapp.js");
    let generated_wasm = staging.join("webapp_bg.wasm");
    let javascript = fs::read_to_string(&generated_js)?;
    let wasm = fs::read(&generated_wasm)?;
    let fingerprint = asset_fingerprint(&[javascript.as_bytes(), &wasm]);
    let javascript_name = format!("webapp_{fingerprint}.js");
    let wasm_name = format!("webapp_bg_{fingerprint}.wasm");
    fs::write(
        staging.join(&javascript_name),
        javascript.replace("webapp_bg.wasm", &wasm_name),
    )?;
    fs::rename(&generated_wasm, staging.join(&wasm_name))?;
    fs::remove_file(&generated_js)?;
    fs::write(
        staging.join("bootstrap.js"),
        format!(
            "// Generated by `cargo site build`; do not edit.\nimport init from './{javascript_name}';\ntry {{ await init(); }} catch (error) {{ document.documentElement.dataset.theme = 'dark'; console.error('Wasm startup failed', error); }}\n"
        ),
    )?;
    replace_directory(&staging, &output, &backup)
}

fn asset_fingerprint(parts: &[&[u8]]) -> String {
    let mut hasher = DefaultHasher::new();
    parts.hash(&mut hasher);
    format!("{:016x}", hasher.finish())
}

fn replace_directory(staging: &Path, output: &Path, backup: &Path) -> Result<()> {
    if backup.exists() {
        fs::remove_dir_all(backup).with_context(|| format!("removing {}", backup.display()))?;
    }
    if output.exists() {
        fs::rename(output, backup)
            .with_context(|| format!("moving {} to {}", output.display(), backup.display()))?;
    }
    if let Err(error) = fs::rename(staging, output) {
        if backup.exists() {
            let _ = fs::rename(backup, output);
        }
        return Err(error).with_context(|| format!("activating {}", output.display()));
    }
    if backup.exists() {
        fs::remove_dir_all(backup).with_context(|| format!("removing {}", backup.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::asset_fingerprint;

    #[test]
    fn asset_fingerprints_change_with_content() {
        assert_ne!(
            asset_fingerprint(&[b"first"]),
            asset_fingerprint(&[b"second"])
        );
        assert_eq!(
            asset_fingerprint(&[b"stable"]),
            asset_fingerprint(&[b"stable"])
        );
    }
}
