//! Cargo-driven development, quality, deployment, and private reporting tasks.

use anyhow::{Context, Result, anyhow, bail};
use serde_json::{Value, json};
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::ffi::OsStr;
use std::fs;
use std::hash::{DefaultHasher, Hash, Hasher};
use std::io::Cursor;
use std::path::{Component, Path, PathBuf};
use std::process::{Command, ExitStatus};
use std::thread;
use std::time::{Duration, SystemTime};
use tiny_http::{Header, Response, Server, StatusCode};
use wasm_bindgen_cli_support::Bindgen;

const RUST_TOOLCHAIN: &str = "1.97.1";

fn main() -> Result<()> {
    let root = workspace_root()?;
    let mut arguments = env::args().skip(1);
    let Some(command) = arguments.next() else {
        print_help();
        return Ok(());
    };
    let remaining: Vec<String> = arguments.collect();
    match command.as_str() {
        "build" => build_all(&root),
        "serve" => serve(&root, &remaining),
        "check" => check(&root),
        "format" => format_sources(&root),
        "analytics" => analytics(&remaining),
        "help" | "--help" | "-h" => {
            print_help();
            Ok(())
        }
        other => bail!("unknown site command `{other}`; run `cargo site help`"),
    }
}

fn print_help() {
    println!(
        "cargo site <command>\n\n  build      build browser Wasm and the static site atomically\n  serve      watch sources and serve http://localhost:8000\n  check      run formatting, Rust checks, tests, build, and source audits\n  format     format Rust, HTML, CSS, TOML, Markdown, and YAML\n  analytics  query private D1 aggregates with --days 1..90 --format table|csv"
    );
}

fn workspace_root() -> Result<PathBuf> {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .context("xtask must be a direct child of the workspace")
}

fn build_all(root: &Path) -> Result<()> {
    build_browser_wasm(root)?;
    let candidate = root.join("target/site-output/current");
    let report = sitegen::build(&sitegen::BuildConfig {
        workspace_root: root.to_path_buf(),
        output_dir: candidate.clone(),
    })?;
    audit(root, &candidate)?;
    replace_directory(
        &candidate,
        &root.join("public"),
        &root.join("target/site-output/public-previous"),
    )?;
    println!(
        "built {} pages at {} (asset key {})",
        report.page_count,
        root.join("public").display(),
        report.cache_key
    );
    Ok(())
}

fn build_browser_wasm(root: &Path) -> Result<()> {
    run(
        rust_cargo().current_dir(root).args([
            "build",
            "--locked",
            "--release",
            "--package",
            "webapp",
            "--target",
            "wasm32-unknown-unknown",
        ]),
        "building browser Wasm",
    )?;

    let input = root.join("target/rustup/wasm32-unknown-unknown/release/webapp.wasm");
    let parent = root.join("target/site-assets");
    let staging = parent.join("wasm-next");
    let output = parent.join("wasm");
    let backup = parent.join("wasm-previous");
    if staging.exists() {
        fs::remove_dir_all(&staging).with_context(|| format!("removing {}", staging.display()))?;
    }
    fs::create_dir_all(&staging).with_context(|| format!("creating {}", staging.display()))?;
    let mut bindgen = Bindgen::new();
    bindgen.input_path(&input).out_name("webapp");
    bindgen.web(true)?;
    bindgen.omit_default_module_path(false);
    bindgen.generate(&staging)?;
    let generated_js = staging.join("webapp.js");
    let generated_wasm = staging.join("webapp_bg.wasm");
    let javascript = fs::read_to_string(&generated_js)?;
    let wasm = fs::read(&generated_wasm)?;
    let fingerprint = asset_fingerprint(&[javascript.as_bytes(), &wasm]);
    let javascript_name = format!("webapp_{fingerprint}.js");
    let wasm_name = format!("webapp_bg_{fingerprint}.wasm");
    fs::write(
        staging.join(&javascript_name),
        javascript.replace("webapp_bg.wasm", &wasm_name),
    )?;
    fs::rename(&generated_wasm, staging.join(&wasm_name))?;
    fs::remove_file(&generated_js)?;
    fs::write(
        staging.join("bootstrap.js"),
        format!(
            "// Generated by `cargo site build`; do not edit.\nimport init from './{javascript_name}';\ntry {{ await init(); }} catch (error) {{ document.documentElement.dataset.theme = 'dark'; console.error('Wasm startup failed', error); }}\n"
        ),
    )?;
    replace_directory(&staging, &output, &backup)
}

fn asset_fingerprint(parts: &[&[u8]]) -> String {
    let mut hasher = DefaultHasher::new();
    parts.hash(&mut hasher);
    format!("{:016x}", hasher.finish())
}

fn replace_directory(staging: &Path, output: &Path, backup: &Path) -> Result<()> {
    if backup.exists() {
        fs::remove_dir_all(backup).with_context(|| format!("removing {}", backup.display()))?;
    }
    if output.exists() {
        fs::rename(output, backup)
            .with_context(|| format!("moving {} to {}", output.display(), backup.display()))?;
    }
    if let Err(error) = fs::rename(staging, output) {
        if backup.exists() {
            let _ = fs::rename(backup, output);
        }
        return Err(error).with_context(|| format!("activating {}", output.display()));
    }
    if backup.exists() {
        fs::remove_dir_all(backup).with_context(|| format!("removing {}", backup.display()))?;
    }
    Ok(())
}

fn serve(root: &Path, arguments: &[String]) -> Result<()> {
    let port = parse_serve_port(arguments)?;
    let address = format!("127.0.0.1:{port}");
    build_all(root)?;
    let watch_root = root.to_path_buf();
    thread::spawn(move || watch_sources(&watch_root));
    let server = Server::http(&address).map_err(|error| anyhow!(error.to_string()))?;
    println!("serving http://localhost:{port}; press Ctrl-C to stop");
    for request in server.incoming_requests() {
        let path = public_path(root, request.url());
        let (status, bytes, content_type) =
            match path.and_then(|path| read_public_file(root, &path)) {
                Ok((bytes, content_type)) => (StatusCode(200), bytes, content_type),
                Err(_) => {
                    let fallback = root.join("public/404.html");
                    let bytes = fs::read(fallback).unwrap_or_else(|_| b"Not found".to_vec());
                    (StatusCode(404), bytes, "text/html; charset=utf-8")
                }
            };
        let header = Header::from_bytes("Content-Type", content_type)
            .map_err(|_| anyhow!("invalid content-type header"))?;
        let content_length = bytes.len();
        let response = Response::new(
            status,
            vec![header],
            Cursor::new(bytes),
            Some(content_length),
            None,
        );
        if let Err(error) = request.respond(response) {
            eprintln!("local response failed: {error}");
        }
    }
    Ok(())
}

fn parse_serve_port(arguments: &[String]) -> Result<u16> {
    match arguments {
        [] => Ok(8000),
        [flag, value] if flag == "--port" => {
            value.parse().context("--port must be a valid TCP port")
        }
        _ => bail!("serve accepts only an optional `--port PORT` argument"),
    }
}

fn watch_sources(root: &Path) {
    let mut previous = source_snapshot(root).unwrap_or_default();
    loop {
        thread::sleep(Duration::from_millis(750));
        let current = source_snapshot(root).unwrap_or_default();
        if current != previous {
            println!("source change detected; rebuilding");
            match build_all(root) {
                Ok(()) => println!("rebuild complete"),
                Err(error) => eprintln!("rebuild failed; serving the last valid build: {error:#}"),
            }
            previous = source_snapshot(root).unwrap_or(current);
        }
    }
}

fn source_snapshot(root: &Path) -> Result<BTreeMap<PathBuf, SystemTime>> {
    let mut snapshot = BTreeMap::new();
    for relative in [
        "content",
        "templates",
        "styles",
        "static",
        "crates/sitegen",
        "crates/webapp",
    ] {
        collect_modified(&root.join(relative), &mut snapshot)?;
    }
    Ok(snapshot)
}

fn collect_modified(path: &Path, output: &mut BTreeMap<PathBuf, SystemTime>) -> Result<()> {
    if path.is_dir() {
        for entry in fs::read_dir(path)? {
            collect_modified(&entry?.path(), output)?;
        }
    } else if path.is_file() {
        output.insert(path.to_path_buf(), fs::metadata(path)?.modified()?);
    }
    Ok(())
}

fn public_path(root: &Path, url: &str) -> Result<PathBuf> {
    let path = url
        .split(['?', '#'])
        .next()
        .unwrap_or("/")
        .trim_start_matches('/');
    let relative = Path::new(path);
    if relative
        .components()
        .any(|component| !matches!(component, Component::Normal(_)))
        && !path.is_empty()
    {
        bail!("invalid request path");
    }
    let mut candidate = root.join("public").join(relative);
    if path.is_empty() || candidate.is_dir() || candidate.extension().is_none() {
        candidate = candidate.join("index.html");
    }
    Ok(candidate)
}

fn read_public_file(root: &Path, path: &Path) -> Result<(Vec<u8>, &'static str)> {
    let public = root.join("public");
    if !path.starts_with(&public) || !path.is_file() {
        bail!("file is outside public output or missing");
    }
    let content_type = match path.extension().and_then(OsStr::to_str).unwrap_or_default() {
        "html" => "text/html; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "js" => "text/javascript; charset=utf-8",
        "wasm" => "application/wasm",
        "png" => "image/png",
        "pdf" => "application/pdf",
        "xml" => "application/xml; charset=utf-8",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    };
    Ok((fs::read(path)?, content_type))
}

fn check(root: &Path) -> Result<()> {
    run(
        rust_cargo()
            .current_dir(root)
            .args(["fmt", "--all", "--", "--check"]),
        "checking Rust formatting",
    )?;
    run_dprint(root, true)?;
    run(
        rust_cargo().current_dir(root).args([
            "clippy",
            "--locked",
            "--workspace",
            "--all-targets",
            "--",
            "-D",
            "warnings",
        ]),
        "checking native Rust targets",
    )?;
    run(
        rust_cargo().current_dir(root).args([
            "clippy",
            "--locked",
            "--package",
            "webapp",
            "--target",
            "wasm32-unknown-unknown",
            "--",
            "-D",
            "warnings",
        ]),
        "checking browser Wasm",
    )?;
    run(
        rust_cargo().current_dir(root).args([
            "clippy",
            "--locked",
            "--package",
            "analytics-worker",
            "--target",
            "wasm32-unknown-unknown",
            "--",
            "-D",
            "warnings",
        ]),
        "checking Cloudflare Worker Wasm",
    )?;
    run(
        rust_cargo()
            .current_dir(root)
            .args(["test", "--locked", "--workspace"]),
        "running Rust tests",
    )?;
    build_all(root)?;
    println!("all checks passed");
    Ok(())
}

fn format_sources(root: &Path) -> Result<()> {
    run(
        rust_cargo().current_dir(root).args(["fmt", "--all"]),
        "formatting Rust",
    )?;
    run_dprint(root, false)
}

fn run_dprint(root: &Path, check_only: bool) -> Result<()> {
    let mut command = Command::new("dprint");
    command.current_dir(root);
    command.arg(if check_only { "check" } else { "fmt" });
    command.arg("--incremental=false");
    match command.status() {
        Ok(status) if status.success() => Ok(()),
        Ok(status) => bail!("dprint exited with {status}"),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            bail!("dprint is required; install the version pinned in .dprint-version")
        }
        Err(error) => Err(error).context("running dprint"),
    }
}

fn run(command: &mut Command, description: &str) -> Result<()> {
    let status: ExitStatus = command.status().with_context(|| description.to_owned())?;
    if !status.success() {
        bail!("{description} failed with {status}");
    }
    Ok(())
}

fn rust_cargo() -> Command {
    let mut command = Command::new("rustup");
    command.args(["run", RUST_TOOLCHAIN, "cargo"]);
    command.env("CARGO_TARGET_DIR", "target/rustup");
    if let Ok(output) = Command::new("rustup")
        .args(["which", "rustc", "--toolchain", RUST_TOOLCHAIN])
        .output()
        && output.status.success()
    {
        let compiler = String::from_utf8_lossy(&output.stdout).trim().to_owned();
        command.env("RUSTC", &compiler);
        if let Some(toolchain_bin) = Path::new(&compiler).parent() {
            let existing_path = env::var_os("PATH").unwrap_or_default();
            let paths = std::iter::once(toolchain_bin.to_path_buf())
                .chain(env::split_paths(&existing_path));
            if let Ok(path) = env::join_paths(paths) {
                command.env("PATH", path);
            }
        }
    }
    command
}

fn analytics(arguments: &[String]) -> Result<()> {
    let mut days = 30_u8;
    let mut format = "table";
    let mut index = 0;
    while index < arguments.len() {
        match arguments[index].as_str() {
            "--days" => {
                index += 1;
                days = arguments
                    .get(index)
                    .context("--days requires a value")?
                    .parse()
                    .context("--days must be an integer")?;
            }
            "--format" => {
                index += 1;
                format = arguments.get(index).context("--format requires a value")?;
            }
            other => bail!("unknown analytics option `{other}`"),
        }
        index += 1;
    }
    if !(1..=90).contains(&days) {
        bail!("--days must be between 1 and 90");
    }
    if !matches!(format, "table" | "csv") {
        bail!("--format must be `table` or `csv`");
    }

    let token = required_secret("CLOUDFLARE_API_TOKEN")?;
    let account = required_secret("CLOUDFLARE_ACCOUNT_ID")?;
    let database = required_secret("CLOUDFLARE_D1_DATABASE_ID")?;
    let endpoint = format!(
        "https://api.cloudflare.com/client/v4/accounts/{account}/d1/database/{database}/query"
    );
    let interval = format!("-{} days", days.saturating_sub(1));
    let body = json!({
        "sql": "SELECT day, route, country_code, region_code, SUM(views) AS views FROM location_page_views WHERE day >= date('now', ?1) GROUP BY day, route, country_code, region_code ORDER BY day DESC, route, country_code, region_code",
        "params": [interval]
    });
    let mut response = ureq::post(&endpoint)
        .header("Authorization", &format!("Bearer {token}"))
        .header("Content-Type", "application/json")
        .send_json(body)
        .context("querying the Cloudflare D1 API")?;
    let payload: Value = response
        .body_mut()
        .read_json()
        .context("decoding the D1 response")?;
    if payload.get("success").and_then(Value::as_bool) != Some(true) {
        bail!("Cloudflare rejected the analytics query");
    }
    let rows = payload
        .pointer("/result/0/results")
        .and_then(Value::as_array)
        .context("D1 response did not contain result rows")?;
    print_analytics(rows, format)
}

fn required_secret(name: &str) -> Result<String> {
    env::var(name).with_context(|| format!("{name} is required for private analytics reports"))
}

fn print_analytics(rows: &[Value], format: &str) -> Result<()> {
    let fields = ["day", "route", "country_code", "region_code", "views"];
    if format == "csv" {
        println!("{}", fields.join(","));
        for row in rows {
            let values = fields.map(|field| csv_cell(&json_cell(row, field)));
            println!("{}", values.join(","));
        }
        return Ok(());
    }
    let mut widths = fields.map(str::len);
    for row in rows {
        for (index, field) in fields.iter().enumerate() {
            widths[index] = widths[index].max(json_cell(row, field).len());
        }
    }
    println!(
        "{:<day_width$}  {:<route_width$}  {:<country_width$}  {:<region_width$}  {:>views_width$}",
        "day",
        "route",
        "country",
        "region",
        "views",
        day_width = widths[0],
        route_width = widths[1],
        country_width = widths[2].max(7),
        region_width = widths[3].max(6),
        views_width = widths[4],
    );
    for row in rows {
        println!(
            "{:<day_width$}  {:<route_width$}  {:<country_width$}  {:<region_width$}  {:>views_width$}",
            json_cell(row, "day"),
            json_cell(row, "route"),
            json_cell(row, "country_code"),
            json_cell(row, "region_code"),
            json_cell(row, "views"),
            day_width = widths[0],
            route_width = widths[1],
            country_width = widths[2].max(7),
            region_width = widths[3].max(6),
            views_width = widths[4],
        );
    }
    Ok(())
}

fn json_cell(row: &Value, field: &str) -> String {
    let Some(value) = row.get(field) else {
        return String::new();
    };
    value
        .as_str()
        .map(str::to_owned)
        .or_else(|| value.as_i64().map(|number| number.to_string()))
        .or_else(|| value.as_u64().map(|number| number.to_string()))
        .unwrap_or_default()
}

fn csv_cell(value: &str) -> String {
    if value.contains([',', '"', '\n']) {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_owned()
    }
}

fn audit(root: &Path, output: &Path) -> Result<()> {
    audit_source_files(root)?;
    audit_worker_privacy(root)?;
    audit_styles(root)?;
    audit_html(output)?;
    Ok(())
}

fn audit_source_files(root: &Path) -> Result<()> {
    let mut files = Vec::new();
    collect_files(root, &mut files, &[".git", "build", "public", "target"])?;
    let forbidden: Vec<_> = files
        .into_iter()
        .filter(|path| {
            matches!(
                path.extension().and_then(OsStr::to_str),
                Some("js" | "jsx" | "ts" | "tsx")
            )
        })
        .collect();
    if !forbidden.is_empty() {
        bail!("handwritten JavaScript or TypeScript is forbidden: {forbidden:?}");
    }
    Ok(())
}

fn audit_worker_privacy(root: &Path) -> Result<()> {
    let worker = root.join("crates/analytics-worker/src");
    let mut files = Vec::new();
    collect_files(&worker, &mut files, &[])?;
    let forbidden = [
        "CF-Connecting-IP",
        "CF-Connecting-IPV6",
        "X-Forwarded-For",
        "X-Real-IP",
        "True-Client-IP",
        "forwarded-for",
        "request.headers",
        "user-agent",
        "referer",
        ".city()",
        ".postal_code()",
        ".latitude()",
        ".longitude()",
        ".cookies()",
    ];
    for file in files {
        let source = fs::read_to_string(&file)?;
        for needle in forbidden {
            if source
                .to_ascii_lowercase()
                .contains(&needle.to_ascii_lowercase())
            {
                bail!(
                    "forbidden visitor-data access `{needle}` in {}",
                    file.display()
                );
            }
        }
    }
    Ok(())
}

fn audit_styles(root: &Path) -> Result<()> {
    for name in [
        "tokens.css",
        "foundation.css",
        "layout.css",
        "components.css",
        "responsive.css",
    ] {
        let path = root.join("styles").join(name);
        let css = fs::read_to_string(&path)?;
        if css.matches('{').count() != css.matches('}').count() {
            bail!("unbalanced CSS blocks in {}", path.display());
        }
        for obsolete in ["theme-control", "nav-control", ":has("] {
            if css.contains(obsolete) {
                bail!("obsolete selector `{obsolete}` in {}", path.display());
            }
        }
    }
    Ok(())
}

fn audit_html(public: &Path) -> Result<()> {
    let mut files = Vec::new();
    collect_files(public, &mut files, &[])?;
    for path in files
        .into_iter()
        .filter(|path| path.extension() == Some(OsStr::new("html")))
    {
        let html = fs::read_to_string(&path)?;
        if !html.to_ascii_lowercase().starts_with("<!doctype html>")
            || !html.contains("<main id=\"content\"")
        {
            bail!("malformed generated document {}", path.display());
        }
        if !html.contains("data-route=\"") {
            bail!("missing route metadata in {}", path.display());
        }
        for attribute in [
            "onclick=",
            "onchange=",
            "oninput=",
            "onkeydown=",
            "onkeyup=",
            "onload=",
        ] {
            if html.to_ascii_lowercase().contains(attribute) {
                bail!("inline event attribute in {}", path.display());
            }
        }
        let scripts: Vec<_> = html.match_indices("<script").collect();
        if scripts.len() != 1
            || !html.contains("<script type=\"module\" src=\"/assets/wasm/bootstrap.js?v=")
        {
            bail!("unexpected script entry point in {}", path.display());
        }
        audit_ids_and_fragments(&path, &html)?;
        audit_local_assets(public, &path, &html)?;
    }
    Ok(())
}

fn audit_ids_and_fragments(path: &Path, html: &str) -> Result<()> {
    let ids: BTreeSet<String> = attribute_values(html, "id=\"").into_iter().collect();
    let id_count = attribute_values(html, "id=\"").len();
    if ids.len() != id_count {
        bail!("duplicate HTML id in {}", path.display());
    }
    for fragment in attribute_values(html, "href=\"#") {
        if !fragment.is_empty() && !ids.contains(&fragment) {
            bail!("broken fragment #{fragment} in {}", path.display());
        }
    }
    Ok(())
}

fn audit_local_assets(public: &Path, path: &Path, html: &str) -> Result<()> {
    for marker in ["src=\"/assets/", "href=\"/assets/"] {
        for value in attribute_values(html, marker) {
            let relative = format!("assets/{}", value.split('?').next().unwrap_or_default());
            if !public.join(relative).is_file() {
                bail!("missing local asset referenced by {}", path.display());
            }
        }
    }
    Ok(())
}

fn attribute_values(input: &str, marker: &str) -> Vec<String> {
    input
        .split(marker)
        .skip(1)
        .filter_map(|rest| rest.split('"').next().map(str::to_owned))
        .collect()
}

fn collect_files(
    path: &Path,
    output: &mut Vec<PathBuf>,
    ignored_directories: &[&str],
) -> Result<()> {
    if path.is_dir() {
        for entry in fs::read_dir(path)? {
            let entry = entry?;
            if entry.file_type()?.is_dir()
                && ignored_directories.contains(&entry.file_name().to_string_lossy().as_ref())
            {
                continue;
            }
            collect_files(&entry.path(), output, ignored_directories)?;
        }
    } else if path.is_file() {
        output.push(path.to_path_buf());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{asset_fingerprint, csv_cell, public_path};
    use std::path::Path;

    #[test]
    fn local_routes_map_to_static_index_files() {
        assert_eq!(
            public_path(Path::new("/workspace"), "/notes/?x=1").unwrap(),
            Path::new("/workspace/public/notes/index.html")
        );
    }

    #[test]
    fn local_server_rejects_parent_traversal() {
        assert!(public_path(Path::new("/workspace"), "/../secret").is_err());
    }

    #[test]
    fn csv_output_escapes_delimiters() {
        assert_eq!(csv_cell("a,b"), "\"a,b\"");
        assert_eq!(csv_cell("plain"), "plain");
    }

    #[test]
    fn asset_fingerprints_change_with_content() {
        assert_ne!(
            asset_fingerprint(&[b"first"]),
            asset_fingerprint(&[b"second"])
        );
        assert_eq!(
            asset_fingerprint(&[b"stable"]),
            asset_fingerprint(&[b"stable"])
        );
    }
}
